import Nav from "@/components/navigation/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Movie Review",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<>
			
			<html lang='en' className={inter.className}>
				<body>
          <Nav></Nav>
          {children}
          </body>
			</html>
		</>
	);
}
