GET http://localhost:5000/movie HTTP/1.1
Content-Type: application/json
###
GET http://localhost:5000/movie/top-rated?page=2 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:5000/movie/696374 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:5000/movie/696374 HTTP/1.1
Content-Type: application/json

{
  "rate" : 4.0,
  "comment": "Fahim fucking dork rated"
}

###
GET http://localhost:5000/movie/search?query=batman&page=2 HTTP/1.1
Content-Type: application/json